import { Language } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  mr: {
    app_name: "AI कृषी मित्र",
    welcome: "स्मार्ट शेतीसाठी आपले सहर्ष स्वागत",
    next: "पुढे",
    login: "शेतकरी लॉगिन",
    enter_mobile: "मोबाईल नंबर",
    get_otp: "OTP मिळवा",
    enter_otp: "OTP टाका",
    submit: "सबमिट",
    profile_title: "माझी माहिती",
    name_label: "पूर्ण नाव",
    village_label: "गाव",
    district_label: "जिल्हा",
    land_label: "जमीन (एकर)",
    crop_label: "प्रमुख पीक",
    dashboard: "डॅशबोर्ड",
    weather: "हवामान",
    disease_check: "रोग निदान",
    soil_health: "जमीन आरोग्य",
    profit: "नफा/उत्पन्न",
    market: "बाजार भाव",
    voice_help: "कृषी मित्र (Voice)",
    upload_photo: "पिकाचा फोटो काढा",
    analyzing: "AI तपासणी करत आहे...",
    result: "तपासणी अहवाल",
    treatment: "उपाययोजना",
    water_status: "पाणी नियोजन",
    market_rate: "बाजार भाव",
    net_profit: "निव्वळ नफा",
    today: "आज",
    humidity: "आद्रता",
    wind: "वारा",
    soil_moisture: "ओलावा",
    irrigation_advice: "पाणी सल्ला",
    irrigation_needed: "पाणी देण्याची गरज आहे",
    irrigation_not_needed: "पाणी देण्याची गरज नाही",
    speak_now: "विचारण्यासाठी बोला",
    listening: "ऐकत आहे...",
    ask_question: "प्रश्न विचारा (उदा. कपाशीवर फवारणी कोणती करावी?)",
    send: "पाठवा",
    back: "मागे",
    logout: "बाहेर पडा",
    commodity: "शेतमाल",
    price: "भाव (₹/क्विंटल)",
    trend: "बदल",
  },
  hi: {
    app_name: "AI कृषि मित्र",
    welcome: "स्मार्ट खेती में आपका स्वागत है",
    next: "आगे",
    login: "किसान लॉगिन",
    enter_mobile: "मोबाइल नंबर",
    get_otp: "OTP प्राप्त करें",
    enter_otp: "OTP डालें",
    submit: "जमा करें",
    profile_title: "मेरी जानकारी",
    name_label: "पूरा नाम",
    village_label: "गाँव",
    district_label: "जिला",
    land_label: "जमीन (एकड़)",
    crop_label: "मुख्य फसल",
    dashboard: "डैशबोर्ड",
    weather: "मौसम",
    disease_check: "रोग निदान",
    soil_health: "मिट्टी स्वास्थ",
    profit: "लाभ अनुमान",
    market: "मंडी भाव",
    voice_help: "कृषि मित्र (Voice)",
    upload_photo: "फसल की फोटो लें",
    analyzing: "AI जाँच कर रहा है...",
    result: "जाँच रिपोर्ट",
    treatment: "उपचार",
    water_status: "जल प्रबंधन",
    market_rate: "बाजार भाव",
    net_profit: "शुद्ध लाभ",
    today: "आज",
    humidity: "नमी",
    wind: "हवा",
    soil_moisture: "मिट्टी की नमी",
    irrigation_advice: "सिंचाई सलाह",
    irrigation_needed: "पानी देने की जरूरत है",
    irrigation_not_needed: "पानी देने की जरूरत नहीं है",
    speak_now: "पूछने के लिए बोलें",
    listening: "सुन रहा हूँ...",
    ask_question: "प्रश्न पूछें...",
    send: "भेजें",
    back: "पीछे",
    logout: "लॉग आउट",
    commodity: "फसल",
    price: "भाव (₹/क्विंटल)",
    trend: "बदलाव",
  },
  en: {
    app_name: "AI Krushi Mitra",
    welcome: "Welcome to Smart Farming",
    next: "Next",
    login: "Farmer Login",
    enter_mobile: "Mobile Number",
    get_otp: "Get OTP",
    enter_otp: "Enter OTP",
    submit: "Submit",
    profile_title: "My Profile",
    name_label: "Full Name",
    village_label: "Village",
    district_label: "District",
    land_label: "Land (Acres)",
    crop_label: "Main Crop",
    dashboard: "Dashboard",
    weather: "Weather",
    disease_check: "Disease Detect",
    soil_health: "Soil Health",
    profit: "Yield & Profit",
    market: "Market Prices",
    voice_help: "Krushi Voice AI",
    upload_photo: "Capture Crop Photo",
    analyzing: "AI Analyzing...",
    result: "Analysis Report",
    treatment: "Treatment",
    water_status: "Water Mgmt",
    market_rate: "Market Rate",
    net_profit: "Net Profit",
    today: "Today",
    humidity: "Humidity",
    wind: "Wind",
    soil_moisture: "Moisture",
    irrigation_advice: "Irrigation Advice",
    irrigation_needed: "Watering Needed",
    irrigation_not_needed: "No Watering Needed",
    speak_now: "Tap to Speak",
    listening: "Listening...",
    ask_question: "Ask a question...",
    send: "Send",
    back: "Back",
    logout: "Logout",
    commodity: "Commodity",
    price: "Price (₹/Qtl)",
    trend: "Change",
  }
};

export const MOCK_WEATHER = {
  temp: 28,
  condition: 'Cloudy',
  humidity: 65,
  forecast: [
    { day: 'Som', temp: 29, icon: '☀️' },
    { day: 'Man', temp: 27, icon: '☁️' },
    { day: 'Bud', temp: 26, icon: '🌧️' },
    { day: 'Gur', temp: 28, icon: '⛅' },
  ]
};